databases:
  - name: brandtrackerdb
    plan: free
    databaseName: brandtracker
    user: brandtracker

services:
  - type: web
    plan: free
    name: brandtracker
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn brandtracker.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: brandtrackerdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2
      - key: USE_LIGHTWEIGHT_NLP
        value: true

